version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./static:/usr/src/app/static
      - ./templates:/usr/src/app/templates
      - ./storage:/usr/src/app/storage
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

